### ISSUE TITLE
Read only mode

### ISSUE THREAD

**Issue by markuskreusch** [cryptomator/cryptofs#11]
Allow to open CryptoFileSystems in read only mode (causing no modifications of the data whatsoever and working on readonly devices). Currently this does not work because the masterkey file is backuped and file channels are opened with write option (#10).

**Comment by markuskreusch** [comment]
Just implemented this in [feature/readonly](https://github.com/cryptomator/cryptofs/tree/feature/readonly). Build and UnitTests are green. I will increase the test coverage and do some manual tests on real readonly filesystems. @overheadhunter  / @tobihagemann may you can do some tests on macOS?

In addition we may add a flag READONLY_AUTODETECT or similar option to do a best effort delegate readonly detection (would check once on fs creation if the delegate filestore or the vault-directory is write protected).

**Comment by overheadhunter** [comment]
> we may add a flag READONLY_AUTODETECT

Due to simplicity I would vote to not add this to CryptoFS but rather let the application that uses CryptoFS check whether the storage location of a vault is writable or not. That way we can keep the CryptoFS initializer parameters as explicit as possible.

**Comment by overheadhunter** [comment]
Tested on macOS and merged
