### ISSUE TITLE
cryptomator returns incorrect sizes for symbolic links

### ISSUE THREAD

**Issue by revintec** [cryptomator/cryptofs#141]
[man stat](https://linux.die.net/man/2/stat):
The `st_size` field gives the size of the file (if it is a regular file or a symbolic link) in bytes. The size of a symbolic link is the length of the pathname it contains, without a terminating null byte.

but cryptomator fails to subtract its encryption header size resulting in incorrect sizes for symbolic links
to test: file `symlink` after `ln -s . symlink` should be 1
it's 1 on native linux FSes, but not 1 on cryptomator fuse FSes

TODO screenshot here

**Comment by revintec** [comment]
see `https://github.com/cryptomator/cryptofs/pull/140` for a possible fix

**Comment by revintec** [comment]
@overheadhunter Hi, I'm using `https://github.com/cryptomator/cli`, and it seems that it haven't been updated for almost a year. can you make a new release thus that this bugfix is included?

**Comment by infeo** [comment]
@revintec Please open an issue in https://github.com/cryptomator/cli
