### ISSUE TITLE
documentation is out of date

### ISSUE THREAD

**Issue by glennhartmann** [cryptomator/cryptofs#157]
The usage examples in the readme:

> ```java
> Obtaining a FileSystem Instance
> You have the option to use the convenience method CryptoFileSystemProvider#newFileSystem as follows:
>
> FileSystem fileSystem = CryptoFileSystemProvider.newFileSystem(
>	storageLocation,
>	CryptoFileSystemProperties.cryptoFileSystemProperties()
>		.withPassphrase("password")
>		.withFlags(FileSystemFlags.READONLY) // readonly flag is optional of course
>		.build());
>
> or to use one of the standard methods from FileSystems#newFileSystem:
>
> URI uri = CryptoFileSystemUri.create(storageLocation);
> FileSystem fileSystem = FileSystems.newFileSystem(
>		uri,
>		CryptoFileSystemProperties.cryptoFileSystemProperties()
>			.withPassphrase("password")
>			.withFlags(FileSystemFlags.READONLY) // readonly flag is optional of course
>			.build());
> ```

do not work, since `class org.cryptomator.cryptofs.CryptoFileSystemProperties.Builder` has no `method withPassphrase(java.lang.String)`

**Comment by infeo** [comment]
Thanks for letting us know. I finally updated the documentation.
