### ISSUE TITLE
Support OneDrives File on Demand feature

### ISSUE THREAD

**Issue by overheadhunter** [cryptomator/cryptofs#18]
Tests show that most Java NIO functions like `Files.list(...)`, `Files.newByteChannel(...)` work normally with on-demand files.

However `Files.isRegularFile(...)` returns `false` for such files, effectively disabling support for OneDrive's _File on Demand_, because we use it to [check if the masterkey is present](https://github.com/cryptomator/cryptofs/blob/1.4.3/src/main/java/org/cryptomator/cryptofs/CryptoFileSystemProvider.java#L182).

**Comment by markuskreusch** [comment]
Any idea how we can detect that a file exists then? IMHO this still is a JDK bug... but if we can workaround it by not using isRegularFile we should do so.

**Comment by overheadhunter** [comment]
While I understand that such a file is not considered "regular", there might be other means. I will test what those methods return for FoD files.

**Comment by vlldk** [comment]
Will this fix the issue with Google Drive File Stream too?

**Comment by overheadhunter** [comment]
@vlldk

> Will this fix the issue with Google Drive File Stream too?

Chances are good, but I can't promise it without testing. If my tests work with OneDrive, I will publish instructions for monkey patching your existing Cryptomator installations, if you want to test the fix.

**Comment by vlldk** [comment]
Ofc - nice tho!
And yes, sure will - thank you

**Comment by vlldk** [comment]
Can confirm, working with OneDrive OD but error with Google Drive File Stream. Log attached. 
[cryptomator0.log](https://github.com/cryptomator/cryptofs/files/1470570/cryptomator0.log)
