### ISSUE TITLE
Restoring a deleted folder in vault causes 'Broken directory file'

### ISSUE THREAD

**Issue by DesmondKong** [cryptomator/cryptofs#20]
## Environment
2 Windows 7 PCs with Cryptomator 1.3.3 and ownCloud Client for vault sync.

## Steps to reproduce
1. On` PC 1`, create new vault.
2. Sync vault and open vault on `PC 2`.
3. On `PC 1`, drag a `folder X` containing a single file into vault. `Folder X` appears on `PC 2`.
4. On `PC 1`, delete `folder X`. `Folder X` disappears on `PC 2`.
5. On `PC 1`, restore `folder X` by dragging into vault again. `Folder X` does not appear on `PC 2` after sync. 

## Expected result
On PC 2, `Folder X` should appear on vault.

## Actual result
On PC 2, `Folder X` does not appear after sync. `Folder X` will appear only when vault is locked and unlocked again.

[Fix #16](https://github.com/cryptomator/cryptofs/issues/16) could be related but did not work in this scenario.

## Log
`WARN  o.c.cryptofs.CryptoDirectoryStream - Broken directory file [redacted]\cvault\d\YY\MTPN4VZHCX7YBMO5H2VTRLRS5JHSQ6\0NIEDU7NAVQ6GQNW7F6MX6NUK32CKM7SBLGRA====. Directory [redacted]\cvault\d\DN\5XWE3MRQFHTJOBY3VLFRZHJ4CN6KDE does not exist.
`

_Thank you!_

**Comment by tobihagemann** [comment]
Just from reading this issue, I can imagine what happens. As far as I know, directory ids are cached. Since you're re-creating the folder (in step 5), the directory gets a new id and the respective directory path is different than before.

As the saying goes:
> There are only two hard things in Computer Science: cache invalidation and naming things.

Not sure what a smart strategy would be to invalidate the directory id cache in this case but I'm fairly certain that this is the issue.

**Comment by DesmondKong** [comment]
It looks like that's the case. The directory gets a new ID in step 5 on `PC 1` and `PC 2` is oblivious to the change. I'm not sure how the caching mechanism works, but is it possible to attempt a reload on the affected directory structure whenever it (broken directory file) happens?

**Comment by markuskreusch** [comment]
Yes, a reload is what we should do in this case.

**Comment by infeo** [comment]
uup, sorry the above commit should reference issue #29...

**Comment by overheadhunter** [comment]
> As far as I know, directory ids are cached. Since you're re-creating the folder (in step 5), the directory gets a new id and the respective directory path is different than before.

Cryptomator 1.3.3 [uses CryptoFS 1.4.5](https://github.com/cryptomator/cryptomator/blob/1.3.3/main/pom.xml#L28).

CryptoFS 1.4.5 [invalidates the cached directory ID](https://github.com/cryptomator/cryptofs/blob/1.4.5/src/main/java/org/cryptomator/cryptofs/CryptoFileSystemImpl.java#L359). Cache invalidation is [still missing for recursive deletion](https://github.com/cryptomator/cryptofs/blob/1.6.2/src/main/java/org/cryptomator/cryptofs/DeletingFileVisitor.java#L42), but it should not be the cause of the problem described in this issue.

**Comment by infeo** [comment]
Broken directory can now be restored via the [health api](https://github.com/cryptomator/cryptofs/blob/develop/src/main/java/org/cryptomator/cryptofs/health/api/HealthCheck.java).
