### ISSUE TITLE
cryptography 

### ISSUE THREAD

**Issue by Khazaeee29** [cryptomator/cryptofs#28]
Which module handle encryption & decryption of webdav files and folders?

**Comment by Khazaeee29** [comment]
How can I use Cryptofs & CryptoLib methods manually for customized target???Is there any java doc for them?

**Comment by overheadhunter** [comment]
Encryption and Decryption of individual files is done by CryptoLib. Example code can be found in the [JavaDoc of the `org.cryptomator.cryptolib` package](http://static.javadoc.io/org.cryptomator/cryptolib/1.2.0/org/cryptomator/cryptolib/package-summary.html).

CryptoFS on the other hand does not do any encryption itself, it merely calls CryptoLib and provides a Java NIO Files interface.
