### ISSUE TITLE
Wrong permissions in read-only mode

### ISSUE THREAD

**Issue by Gregvh** [cryptomator/cryptofs#35]
When using the read-only mode, files and directories are still shown as read-write.
Would it not be better to show them as read-only?

**Comment by infeo** [comment]
interesting... also checked this and in my case the "read-only" state fails.

i accessed a vault via the dokany-nio-adapter and added in the building phase of the CryptoFilesystem the read-only flag. Nonetheless the files were not shown as read-only and i was able to modify the files in the vault. So i guess there is still some work left to do. 
I couldn't find the reason why the files are not shown read-only, but for the ability to modify them i think the methods in https://github.com/cryptomator/cryptofs/blob/develop/src/main/java/org/cryptomator/cryptofs/CryptoFileSystemProvider.java must be changed.

**Comment by overheadhunter** [comment]
Currently CryptoFS simply reports the permissions of the ciphertext files (which are _never_ explicitly set to be read-only):

https://github.com/cryptomator/cryptofs/blob/0b0c9f86cafce77808fdd56e9ee52151a8926a17/src/main/java/org/cryptomator/cryptofs/DelegatingPosixFileAttributes.java#L32-L35

https://github.com/cryptomator/cryptofs/blob/0b0c9f86cafce77808fdd56e9ee52151a8926a17/src/main/java/org/cryptomator/cryptofs/DelegatingDosFileAttributes.java#L18-L21

To fix this, we should override the returned permissions of those methods in `CryptoPosixFileAttributes` and `CryptoDosFileAttributes` _if_ CryptoFS is run in read-only mode. 

To determine this, we should make the `FileSystemFlags` injectable.

**Comment by overheadhunter** [comment]
Will merge this onto develop, once we've successfully updated our build config (we're switching from maven central to bintray jcenter, but need to migrate a few things first...)

**Comment by Gregvh** [comment]
https://github.com/cryptomator/cryptofs/blob/f9f9dbd9ee3f59ce39d10dec20789f0d8c318300/src/main/java/org/cryptomator/cryptofs/CryptoPosixFileAttributes.java#L44-L45
I think READ permissions are not enough, EXECUTE permissions are needed as well for directories to be able to read files inside them.

**Comment by overheadhunter** [comment]
> I think READ permissions are not enough, EXECUTE permissions are needed as well for directories to be able to read files inside them.

Yes, you're absolutely right! This needs to be fixed in 1.6.1
