### ISSUE TITLE
Remove channel funneling

### ISSUE THREAD

**Issue by overheadhunter** [cryptomator/cryptofs#43]
At the moment multiple simultaneous cleartext file channels can be created for a single file. OpenCryptoFile instances are responsible for synchronizing access to the single ciphertext file channel that is being opened internally.

The downside of the current implementation is, that OpenCryptoFile needs to open the ciphertextfile for reading _and_ writing, even if the corresponding cleartext file channel is only opened for reading. This prevents the user from removing write permissions from a file.

~~In order to open a channel read-only, we need to introduce a read-write-lock on the OpenCryptoFile level. I.e. there can be multiple threads reading at the same time using a shared read lock, while a file is locked exclusively as soon as it's opened for writing.~~ Edit: Instead we should create one ciphertext channel per cleartext channel, so we can open the ciphertext channel with exactly those permissions requested for the cleartext channel. CryptoFS should no longer funnel cleartext access into a single ciphertext channel.

This allows us to pass through permissions between the underlying file system and the cleartext NIO file system.

**Comment by overheadhunter** [comment]
We still get a lot of warnings:

```
WARN org.cryptomator.cryptofs.CryptoBasicFileAttributes - Unable to calculate cleartext file size for /path/to/vault/d/2S/LMVHG7QEFW6ZRKLJ2XBBD6ZBYLAJBV/5AZNFOMKHPTRKCPWYHKXDO54PIH2LV7XNTPGYJLMXVY4AS24EY4Q====.
java.lang.IllegalArgumentException: expected ciphertextSize to be positive, but was -88
```

This is due to the fact that the file header is not written when a file channel is opened and directly closed (without actually writing anything).

**Comment by overheadhunter** [comment]
@cryptomator/windows: Just tested with Dokany. It works, but I get lots of messages like this:

```
DEBUG org.cryptomator.frontend.dokany.ReadWriteAdapter - (1490) readFile(): Unable to find handle for /postcard_16.jpg. Try to reopen it.
```

This might not be related to cryptofs, in which case we can merge this feature branch onto develop.

**Comment by infeo** [comment]
@overheadhunter not related to cryptofs, you can merge the feature
