### ISSUE TITLE
Increase threshold before long filenames get inflated

### ISSUE THREAD

**Issue by infeo** [cryptomator/cryptofs#60]
Version: 1.8.6

## Short Description
Increase performance and compability of cryptofs by increasing the treshold before ciphertext filenames are shortend.

## Description
To keep compability with certain OS (e.g. Windows), cryptofs shortens the name of ciphertext files if their base64 encoding exceeds a certain treshold. Currently the treshold is set to 
https://github.com/cryptomator/cryptofs/blob/851f44090db4b068c7ac7fe27adcecd4c32767e5/src/main/java/org/cryptomator/cryptofs/Constants.java#L18 .

If the treshold is increased, file name shortening appears less which makes cryptofs more robust to race conditions, increases the performance due to direct file access and makes it more compatible with certain cloud syncing software (Google BackUp & Sync).

The suggestion is to set it to 254 as the new value.
It is computed the following way: 
1. 248 (Multiple of 8 which is less than the Windows MAX_PATH limit (260) due to base64 encoding)
1. +2 (addtional prefix indicating symbolic links or directories)
1. +4 (file extension)

**Comment by overheadhunter** [comment]
For the record: 4 chars file extension is just reserved for future use, so we don't need to migrate filenames if we decide to add an extension (see #54).

**Comment by overheadhunter** [comment]
For the record: 248 ciphertext bytes leave us with 155 cleartext bytes.

The maximum cleartext filename before shortening happens is this long:

`e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855e3b0c44298fc1c149afbf4c.txt`

**Comment by overheadhunter** [comment]
Filenames must be encrypted deterministically, otherwise we break directory listings. By changing the shortening threshold we break this rule.

Therefore this change requires a new vault format version, otherwise we'd break compatibility with other applications (such as our mobile apps or @iterate-ch's Cyberduck and Mountain Duck).

Therefore we defer this issue to a different minor version.

**Comment by overheadhunter** [comment]
The maximum filename length on many file systems and/or clouds is 255. But: We need to leave some space for a cloud service to add some `(conflict 2018-08-21 00-22-09)` suffix. Let's say we want to reserver 33 chars.

This leaves us with 222 usable chars for prefix (2 chars), encoded ciphertext (216 chars) and extension (4 chars). 216 chars in base32 encoding is equivalent to 135 bytes of ciphertext. Subtracting the IV this gives us 119 cleartext chars.

---

If we have to migrate every filename anyway (see #64), we might want to switch to base64. With the same 222 usable chars our 216 encoded ciphertext chars are now equivalent to 162 ciphertext bytes or 146 cleartext bytes.

On [aforementioned _PDL-Home_](https://github.com/cryptomator/cryptofs/issues/60#issuecomment-522223667) this reduces the likelihood of name shortening even further, only 0.001% of all files would have been affected from shortening.

**Comment by overheadhunter** [comment]
Trying to get some more data from our users [here](https://community.cryptomator.org/t/how-long-are-your-file-names/4085?u=overheadhunter).

**Comment by overheadhunter** [comment]
## Syncing with OneDrive :white_check_mark:
1. Created new vault "format7" inside OneDrive on Windows 10 1803
2. Created new file with 146 chars filename, resulting in a 220 char ciphertext name. Full path is `C:\Users\Sebastian\OneDrive\format7\d\IX\LPPQAPWUNCQTWROJY734VIT7YTQEGM\xr3BnomfWSZLqb13EBi1zwXu34xDwQQtPTkqmSYvtBW6Qg9ae4FIDHP7ByJFdKSJfqwFfWiUojKIlHxCwD8a5U6yojKfAPftXWiAYIo9dQthCC16M3uxkIzaPrDET6-2yuHCX8gECd0LdbMC-qDi1LOxj4koqQbfsAGnhoQ6_SOgKdn3dQWaInAo1AUx7aMP5soJ0Xai1OKpykak3vgB4QK7.c9r`.
3. Synced from Windows using OneDrive 19.152.0801.0008 to macOS using OneDrive 19.152.0801.0007
