### ISSUE TITLE
Vault format 7

### ISSUE THREAD

**Issue by overheadhunter** [cryptomator/cryptofs#64]
Related to #54 and #60.

Vault format 7 should include two changes:
- Increase filename shortening threshold (see #60)
- Reencode filenames from BASE32 to BASE64 (url-safe)
- Introduce a filename suffix `.c9r` for unshortened files (preparation to #54) to fix a problem with Google Drive described in cryptomator/cryptomator#891
- `.lng` file suffix will no longer be used. Instead shortened filenames will get the `.c9s` suffix

---

```sh
.
├─ d
│  ├─ BZ
│  │  └─ R4VZSS5PEF7TU3PMFIMON5GJRNBDWA
│  │     ├─ 5TyvCyF255sRtfrIv__83ucADQ==.c9r  # regular file
│  │     ├─ FHTa55bH_sUfVDbEb0gTL9hZ8nho.c9r  # irregular file...
│  │     │  └─ dir.c9r  # ...which is a directory
│  │     ├─ gLeOGMCN358_UBf2Qk9cWCQl.c9r  # irregular file...
│  │     │  └─ symlink.c9r  # ...which is a symlink
│  │     ├─ IjTsXtReTy6bAAuxzLPV9T0k2vg=.c9s  # shortened name...
│  │     │  ├─ contents.c9r  # ...which is a regular file
│  │     │  └─ name.c9s  # ...mapping to this full name
│  │     ├─ q2nx5XeNCenHyQvkFD4mxYNrWpQ=.c9s  # shortened name...
│  │     │  ├─ dir.c9r  # ...which is a directory
│  │     │  └─ name.c9s  # ...mapping to this full name
│  │     ├─ u_JJCJE-T4IH-EBYASUp1u3p7mA=.c9s  # shortened name...
│  │     │  ├─ name.c9s  # ...mapping to this full name
│  │     │  └─ symlink.c9r  # ...which is a symlink
│  │     └─ ...
│  └─ FC
│     └─ ZKZRLZUODUUYTYA4457CSBPZXB5A77
│        └─ ...
├─ masterkey.cryptomator
└─ masterkey.cryptomator.DFD9B248.bkup
```

**Comment by overheadhunter** [comment]
Migrator needs to make sure exceptions during rename are handled (e.g. by reattempting with a "conflict" name). Also it should clean up `.lng` files which will no longer be required beginning with version 7.

**Comment by overheadhunter** [comment]
Filename migration (per each file) should work like this:

1. strip filename into its parts (prefix `pre`, base32-encoded ciphertext `b32`, suffix `suf`, optional old extension `.lng`)
2. inflate filename if deflated (`.lng`)
3. reencode `b32` to `b64`
4. reassemble canonical filename `c` = `b64` + `.c9r`
5. optionally deflate canonical filename if new threshold (#60) is exceeded `d` = `base64(sha1(c))` + `.c9s`
6. reassemble actual filename by adding `pre` and `suf` to `c` or `d`

These migration steps need to be implemented test-driven.

**Comment by overheadhunter** [comment]
Oh, also: When using base64, our dir and symlink prefixes need to be redefined (see #38).

**Comment by overheadhunter** [comment]
As long as they are case-preserving (to my knowledge all modern file systems are), yes.

**Comment by lellis1936** [comment]
I saw an earlier posting about using GCM encryption for files.  Has a decision been made to stick with CTR mode for this new release (I am playing with 1.5 alpha 2 and I see file ciphertext did not change during migration).

**Comment by overheadhunter** [comment]
@lellis1936 Correct, 1.5.0 will not change file content encryption. For 2.0 we will create a new scheme, GCM is atm the most likely candidate for file content encryption. This is a long-term goal that is currently discussed with many parties.

**Comment by lellis1936** [comment]
I think GCM is an excellent choice.  I can only speak directly about the Windows platform.

On the Windows/Intel platform, GCM very very fast through the CNG API.  Although not supported directly in the managed .Net framework, it _is_ supported directly by .Net 3.0.   And there is always the Win32 Bcrypt CNG support in Windows.

**Comment by overheadhunter** [comment]
It sure is. At the time we chose the ciphers, GCM didn't get hardware-accelerated and therefore was slower than CTR+HMAC. In the meantime this has changed, that's why we plan to offer GCM in 2.0.

However changing the cipher of file content encryption means we need to decrypt and re-encrypt _every_ file. Some users have tens - hundreds of GB, partially stored on remote storage with (relatively) low bandwidth and latency. As CTR+HMAC works just fine and the cipher isn't the bottleneck, there is no reason to enforce such a change in a minor release.
