### ISSUE TITLE
Ignore AppleDouble files in conflict resolver

### ISSUE THREAD

**Issue by tobihagemann** [cryptomator/cryptofs#73]
It's possible that a vault contains AppleDouble files, e.g. dir listing of `/d/RK/YBUSGFH2JNP2ZEIHYZ6UUT5N4XWAHK`:

```
._4bycopA9c4SHxhbNUTmRJLLtv2w=.c9s
._Eah1siezAbrwLIpqxYKT6Bn6fxIb-Q==.c9r
._I84ZuTskwmj5mefWsY4rRizPniVM5Pak6GCd.c9r
._Ns9d42_a2hqahCXKaqw6j2es2z9ltcnfkl1av5I=.c9r
._UryCrt5aaaIlUSOM-MTKR34a5VjngZ1cQ3dhVxmrpuDiR8k=.c9r
._mH5MWFAdV_x91fK9qsdSSXBujPIqMG_8EGLffRBjDdJw.c9r
._rFKluOq-zlvVkNu9CXNt9QGlw4I_B4g6Hqt6gKYeaYdy.c9r
4bycopA9c4SHxhbNUTmRJLLtv2w=.c9s
Eah1siezAbrwLIpqxYKT6Bn6fxIb-Q==.c9r
I84ZuTskwmj5mefWsY4rRizPniVM5Pak6GCd.c9r
Ns9d42_a2hqahCXKaqw6j2es2z9ltcnfkl1av5I=.c9r
UryCrt5aaaIlUSOM-MTKR34a5VjngZ1cQ3dhVxmrpuDiR8k=.c9r
mH5MWFAdV_x91fK9qsdSSXBujPIqMG_8EGLffRBjDdJw.c9r
rFKluOq-zlvVkNu9CXNt9QGlw4I_B4g6Hqt6gKYeaYdy.c9r
```

The conflict resolver sees `_` as a possible delimiter for conflict files and then resolves the filename. However, AppleDouble files should be ignored instead.

I reproduced this issue by copying a vault from Dropbox into WebDAV.

**Comment by overheadhunter** [comment]
I'd even go as far as blacklisting any files starting with `.`. After all, cloud storage providers have to assume those files will be hidden on most systems and therefore they will not choose to name a conflicting file in such a way.
