### ISSUE TITLE
Symbolic links have size -1

### ISSUE THREAD

**Issue by infeo** [cryptomator/cryptofs#74]
The CryptoBasicFileAttributes class is a wrapper for [BasicFileAttributes](https://docs.oracle.com/javase/8/docs/api/java/nio/file/attribute/BasicFileAttributes.html) to show basic properties of the encrypted files.

During construction the type of the ciphertext file is important to determine the size of the requested cleartext file:
https://github.com/cryptomator/cryptofs/blob/4ec6f2f33cb818229e6900fe7dc2e5dfac331591/src/main/java/org/cryptomator/cryptofs/attr/CryptoBasicFileAttributes.java#L38-L52

As one can see in the code, if the file cleartext file is supposed to be a symbolic link, the file size is set to -1.

But since symbolic links are also files, _they do have a strict positive size_ (see for example [here](https://unix.stackexchange.com/questions/2928/do-symbolic-links-actually-make-a-difference-in-disk-usage) or [there](https://askubuntu.com/questions/630986/what-does-the-size-of-a-symlink-represent-in-ls-output)). This leads to unwanted behaviour like described in https://github.com/cryptomator/cryptomator/issues/1092#issuecomment-611621634.

**Comment by overheadhunter** [comment]
We'll return `delegate.size()` instead.
