### ISSUE TITLE
Check file path length limitations of underlying file systems on the fly

### ISSUE THREAD

**Issue by overheadhunter** [cryptomator/cryptofs#77]
This will partly rollback #70 and replace it with a different solution:

Frankly speaking, the upfront capability check in its current form was a mistake. While it prevents data losses, it causes more problems than it solves, as many users are affected by file systems being read-only, while most of their files are not even hitting the limits of the underlying file system.

We therefore propose a different solution, inspired by @amigagamer in cryptomator/cryptomator#1116.

## Maximum Path Length in a Vault Directory
 Starting at the vault's root, the maximum path length will consist of:
* 1 char `d`
* 2 chars `d/xx`
* 30 chars `d/xx/yyyyyyyyyyyyyyyyyyyyyyyyyyyyyy`
* [up to 220 chars](https://github.com/cryptomator/cryptofs/issues/60#issuecomment-523238303) of the `.c9r` file: `d/xx/yyyyyyyyyyyyyyyyyyyyyyyyyyyyyy/zz...zzz.c9r`
* up to 11 chars for type-specific files: `d/xx/yyyyyyyyyyyyyyyyyyyyyyyyyyyyyy/zz...zzz.c9r/symlink.c9r`
  (`contents.c9r` is technically 12 chars, but will only occur in shortened files)

If we also count the path separators, we get 4 additional chars, which gives us a total of 268 ASCII characters.

## Idea

Let there be a new directory called `c/temporary-filesystem-capability-check-dir/nnn/` inside our vault directory. Due to a "happy coincidence" this happens to be equally long as `d/xx/yyyyyyyyyyyyyyyyyyyyyyyyyyyyyy/symlink.c9r/`.

So regardless of the filename length, we can now test the supported path length in this `c` dir, before we do any I/O on the `d` dir.

```
.
├── c
│   └── readme.txt
│   └── temporary-filesystem-capability-check-dir
│       └── 076
│       └── 172
│       └── ...
│       └── 268
│           └── zz...zzz.c9r
├── d
    └── xx
        └── yyyyyyyyyyyyyyyyyyyyyyyyyyyyyy
            └── zz...zzz.c9r
                └── symlink.c9r
```

There can be an optional readme file explaining to the user what this dir is all about and that he can safely delete it manually.

## Proposal

Let there be a _knownToWork_ variable, initially set to 0 when a new vault is added. Before a vault can be unlocked, this _knownToWork_ variable needs to be determined (for details, see below).

Whenever a new file comes into existence, be it via "create" or "move" (or any other operations that I am not thinking of right now), we have to distinguish two cases:
1. if the new (ciphertext) file name is shorter than or equal to _knownToWork_, just proceed normally.
2. if it is longer than _knownToWork_, throw a checked IOException that can be handled by downstream library users, so they can inform users that the cleartext file name was too long.

## Determining _knownToWork_

This variable can be determined using a "binary search" approach:
1. set two variables for upper and lower bounds to the minimum and maximum path lengths that can occur
2. check if a path using `(upper + lower) / 2` chars is supported. If true, set new lower bound to mid and repeat. Otherwise set new upper bound to mid and repeat.
3. Return _knownToWork_ as soon as bounds collide

## Adjusted Migrator

If _knownToWork_ is equal to (or greater than - even though we won't test this) the maxium path length of 268 chars, just proceed migration.

Otherwise do a full recursive directory scan of the vault and see if there are actually any files that would hit the limit of _knownToWork_. In this case cancel the migration with a meaningful exception and inform the user to migrate manually (i.e. copy vault contents from old version).

**Comment by amigagamer** [comment]
Suggestion on the "Adjusted Migrator."

Do an Initial scan to find long path/filenames already identified by Vault format 6 (use m folder for speed??)
Identify and attempt to convert the Longest file First.
If successful :  " _KnownToWork_  "can be immediately set to the longest current filename in vault - safe to proceed with migration.

If fail : cleanly terminate job before the vault is upgraded. (Notify user of conflicts? offer to rename?)

**Comment by overheadhunter** [comment]
> use m folder for speed?

Not a bad idea. Since we're migrating from base32 to base64, filenames get shorter. Therefore only old `.lng` names have the potential of becoming longer than any previously existing filename.

> If fail : cleanly terminate job before the vault is upgraded. (Notify user of conflicts? offer to rename?)

We haven't decided how to deal with such cases yet. The safest way would be to just cancel with an error and instructing the user to manually migrate (i.e. move files out of old vault and into a newly created vault).

**Comment by overheadhunter** [comment]
Here are some findings from testing on Windows 10 18.03 using Jshell from AdoptOpenJDK 11.0.7 and AdoptOpenJDK 14.0.1 with two different WebDAV cloud services that we know to behave differently:

Our test _testFileName_ is ` W:\aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa` (each path fragment is 100 chars)

### Creating a fiel using _testFileName_
Fails on _some_ WebDAV mounts. On others it works without errors and can later even be renamed again.

TODO @SailReal: Test behaviour on eCryptFS

### Moving a file from a short filename to _testFileName_
Fails on _some_ WebDAV mounts. On others it works without errors and can later even be renamed again.

TODO @SailReal: Test behaviour on eCryptFS

### Doing a directory listing on the parent dir, which contains _testFileName_
Reliably fails on Windows throwing an exception:

```
Exception java.nio.file.DirectoryIteratorException: java.nio.file.FileSystemException: W:\aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa: The filename or extension is too long
        at WindowsDirectoryStream$WindowsDirectoryIterator.readNextEntry (WindowsDirectoryStream.java:179)
        at WindowsDirectoryStream$WindowsDirectoryIterator.next (WindowsDirectoryStream.java:217)
```

TODO @SailReal: Test behaviour on eCryptFS

**Comment by infeo** [comment]
I tested on a Ubuntu 18.04 vm the file name length inside an ecryptFS encrypted folder using Jshell from AdoptOpenJDK 11.0.7 and AdoptOpenJDK 14.0.1.

Summary: In all cases an file system exception was thrown reliably with the message "Filename too long" using a file _name_ length above 144. This confirms the bounds stated for ecryptfs in [this article](https://unix.stackexchange.com/questions/32795/what-is-the-maximum-allowed-filename-and-folder-size-with-ecryptfs/32834#32834).

Below this threshold no issues appeared.

**Comment by overheadhunter** [comment]
Just for the record: It is important that our custom `FileNameTooLongException` extends `java.nio.file.FileSystemException` and contains the string "too long" in its reason:

https://github.com/cryptomator/cryptofs/blob/a3c999badb04ea970a0b33634594c84ef89e4c1d/src/main/java/org/cryptomator/cryptofs/FileNameTooLongException.java#L12-L18

This way, other libraries (such as webdav-nio-adapter-servlet, fuse-nio-adapter, dokany-nio-adapter or third parties) don't need cryptofs as a compile-time dependency and can still catch `FileSystemException` filtered for the string "too long", which complies with other native implementations:

```
java.nio.file.FileSystemException: path/of/long/file.txt: The filename or extension is too long
    at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:92)
    at java.base/sun.nio.fs.WindowsException.asIOException(WindowsException.java:112)
```

```
java.nio.file.FileSystemException: path/of/long/file.txt: File name too long
    at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:100)
    at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
```
