### ISSUE TITLE
Vault Format 7 is inefficient for loading metadata

### ISSUE THREAD

**Issue by yiyangc91** [cryptomator/cryptofs#82]
### Summary

Under the new vault format, directories no longer have a `0` prepended to the filename. Instead, to denote anything other than a file, the metadata is basically stored as either a `symlink.c9r` or `dir.c9r` file in the directory.

This poses a bunch of problems:
1. If I write a cryptomator client, and I want to render directories and symlinks separately, I need to traverse into every single directory and load the files. With a folder of hundreds of subfolders, this is excessively slow.
2. On Google Drive, you can potentially set your cloud client to a mode where files are not removed remotely on deletion. Now in a situation where we're not deliberately trying to break things, this is fine, since that means receivers will just see all the files you've deleted. But what if you delete a directory, and replace it with a symlink with the exact same name? Now you have both a `dir.c9r` and `symlink.c9r` in the same folder. What happens now?
3. Actually the above can potentially happen in any distributed system even if you haven't set that particular option, thanks eventual consistency.
4. For `c9s` files, now you need to load the directory, as well as the two files in the directory to even just read the name and open it.

See: https://github.com/cryptomator/cryptomator-android/issues/205

To put it simply, vault version 6 treats the filename as metadata. Vault version 7 changes that and shuffles the metadata into the subdirectory, which makes this suuuuper slow over an internet connection.

### Motivation

Vault Format 7 is inefficient.

### Considered Alternatives

The proposal is to go back to what vault version 6 was doing and store metadata in the filename. I mean to be a little better than vault format 6, maybe you could compact everything into 24 bits, which also allows a bunch of extensibility around loading metadata at list time.

```
- [7 bits (128 values) to denote the type of file, (directory, file, symlink)]
- [1 bit to denote `lng` files]
- [2 bits to allow 'cycling' of the filename, e.g. working around crappy Google Drive behavior.]
- [1 bit to put memes as thumbnails of the files, or whatever]
- [13 bits to just hang around and do nothing with, or to use it as burner data, I dunno]
```

Use a modified Base64 for filename that replaces / with -, base64 the whole thing, and you get 4 filename friendly characters.

Anyway that's just an example.

**Comment by tobihagemann** [comment]
Oh, I'm just now seeing this issue. Basically, I said the same things here: https://github.com/cryptomator/cryptomator-android/issues/205#issuecomment-630711432

Point 2 will always be a problem. If you have a directory and a symlink in vault format 6, you could potentially also have `0...` and `1S...` in the same directory even though the cleartext names are identical.

**Comment by yiyangc91** [comment]
> Storing those information in the filename was in fact a terrible choice in the first place. It meant that the filenames weren't 100% deterministic and we had to make lookup requests for every possible (i.e. up to three) filename(s).

Yeah that's true. I suppose by having metadata in the filename you can also run into having potentially duplicate filenames in (2) too.

**Comment by yiyangc91** [comment]
> That said, what you described under 2. is debatable. But why shouldn't Google (or any other storage provider) delete a file if it is told to?

Missed this. I don't think cloud providers _should_ do that, but if you look at the Google Drive client on windows, there is an option to "ask before removing files" which can possibly be missed by a less tech savvy user (totally hypothetical).

I don't think cryptomator should solve for users configuring their sync clients this way, so it's all good.

I agree that having deterministic filenames is a way better idea. I can't think of any other good solutions that aren't huge hacks. Feel free to close this issue.

**Comment by overheadhunter** [comment]
Oh ok now I understand. Yes, I agree there isn't too much we can do about this. While in theory this can indeed happen, I guess the chance of this is pretty low. A user needs to delete a directory, ignore the sync client warning and create a symlink instead. Even if this did happen, all data is still retained (but needs cleanup).
