### ISSUE TITLE
Masterkey backup strategies: Not all cases covered.

### ISSUE THREAD

**Issue by infeo** [cryptomator/cryptofs#88]
With https://github.com/cryptomator/cryptofs/issues/86, cryptofs can now also unlock vaults located on read-only storage devices.

But the fix is very narrow implemented:
https://github.com/cryptomator/cryptofs/blob/d1be7a7e4cf5c24837556767b4596807c2843947/src/main/java/org/cryptomator/cryptofs/common/MasterkeyBackupHelper.java#L58-L63

Only if the write operation returns  `AccessDeniedException` we check for an alternative. But some file systems are sloppy regarding the specifc errors leading up to just throwing an `IOException` with a message like  "Permission Denied".

Hence we should just catch any IOException and try the workaround. If this one also fails, nothing is lost because the underlying filesystems seems broken and if not, the caller has (maybe only read) access to the encrypted files.

**Comment by overheadhunter** [comment]
I'd suggest to open the channel with `[WRITE, CREATE_NEW]` instead of `[WRITE, CREATE, TRUNCATE_EXISTING]` and then catch:

```java
} catch (FileAlreadyExistsException e) {
  assertExistingBackupMatchesContent(...); // which should no longer check if the file exists but rather rely on it
} catch (IOException e) {
  LOG.warn("Failed to create backup yada yada");
}
```

---

I also suggest to rename `backupMasterKey(...)` to `attemptMasterkeyBackup(...)` to denote the best-effort character of this method.

**Comment by infeo** [comment]
But what if the existing backup is corrupted and the masterkey file is correct? In this setup the unlock will also fail even thou the password is correct because the backup file exists, but we only compare masterkey to backup file.

Additionally, the downstream problem might not be fixed by this, because it is on unclear from the API which exception is thrown first (AccessDeniedException or FileAlreadyExistsException). But this should not be taken too much into consideration.

**Comment by overheadhunter** [comment]
> But what if the existing backup is corrupted and the masterkey file is correct?

In that case you'd indeed _just_ get a warning logged. I wouldn't say that the existing solution is superior per se, though. Write can still fail half-way. An absolutely bullet-proof way of writing the file would include a tmp file, a consistency check and an atomic move replacing the old file.

> because it is on unclear from the API which exception is thrown first (AccessDeniedException or FileAlreadyExistsException).

Why does the order matter? AccessDenied will be caught by the more generic catch block.

**Comment by infeo** [comment]
> Why does the order matter? AccessDenied will be caught by the more generic catch block.

That is... true.^^

I'll open a PR for this. Maybe even implement the "proper" backup strategy by creating temporary file.
